# Generated by Django 3.2.6 on 2022-09-02 20:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import productApp.choices
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified at')),
            ],
        ),
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('itemPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='checkOut',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('totalPrice', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], default=productApp.choices.orderStatus['PENDING'], max_length=128, verbose_name='Status')),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
