# Generated by Django 3.2.6 on 2022-09-02 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.card'),
        ),
        migrations.AddField(
            model_name='carditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.product'),
        ),
        migrations.AddField(
            model_name='card',
            name='items',
            field=models.ManyToManyField(related_name='_productApp_card_items_+', to='productApp.cardItem'),
        ),
    ]
